"""initial schema

Revision ID: 45d8846d6772
Revises: 
Create Date: 2026-07-03 20:56:07.131185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d8846d6772'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('commission_percent', sa.Integer(), nullable=False),
    sa.Column('open_registration_patients', sa.Boolean(), nullable=False),
    sa.Column('open_registration_professionals', sa.Boolean(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('alert_no_response', sa.Boolean(), nullable=False),
    sa.Column('alert_daily_report', sa.Boolean(), nullable=False),
    sa.Column('alert_pending_payment', sa.Boolean(), nullable=False),
    sa.Column('alert_low_rating', sa.Boolean(), nullable=False),
    sa.Column('alert_new_professional', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialties',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PATIENT', 'PROFESSIONAL', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('admins',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('allergies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('chronic_conditions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('current_medications', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('professionals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('sub_specialties', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING_DOCS', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED', name='professionalstatus'), nullable=False),
    sa.Column('availability', sa.Enum('ONLINE_NOW', 'SCHEDULED_ONLY', 'OFFLINE', name='availabilitymode'), nullable=False),
    sa.Column('auto_availability', sa.Boolean(), nullable=False),
    sa.Column('appointment_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price_general', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_urgent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_follow_up', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_ratings', sa.Integer(), nullable=False),
    sa.Column('total_consultations', sa.Integer(), nullable=False),
    sa.Column('cmb_matricula', sa.String(length=50), nullable=True),
    sa.Column('sedes_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('sub_specialties',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('specialty_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('consultation_type', sa.Enum('IMMEDIATE', 'SCHEDULED', 'FOLLOW_UP', name='consultationtype'), nullable=False),
    sa.Column('status', sa.Enum('AGENT_TRIAGING', 'PROFESSIONAL_ACCEPTED', 'WAITING_PAYMENT', 'PAYMENT_CONFIRMED', 'WAITING_PROFESSIONAL', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='consultationstatus'), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('agent_summary', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('reschedule_proposed_at', sa.DateTime(), nullable=True),
    sa.Column('reschedule_proposed_by', sa.String(length=20), nullable=True),
    sa.Column('reschedule_used', sa.Boolean(), nullable=False),
    sa.Column('reschedule_attempts', sa.Integer(), nullable=False),
    sa.Column('outcome_note', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('video_room_id', sa.String(length=255), nullable=True),
    sa.Column('video_room_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('professional_earning', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional_docs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('doc_type', sa.Enum('CI_FRONT', 'CI_BACK', 'PROFESSIONAL_TITLE', 'ACADEMIC_DIPLOMA', 'HEALTH_MINISTRY', 'SEDES_REGISTRATION', 'CMB_MATRICULA', 'SPECIALTY_CERT', 'SELFIE_WITH_CI', name='doctype'), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='docstatus'), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialty_proposals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('SPECIALTY', 'SUB_SPECIALTY', name='proposaltype'), nullable=False),
    sa.Column('proposed_name', sa.String(length=100), nullable=False),
    sa.Column('parent_specialty_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('parent_proposal_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_proposal_id'], ['specialty_proposals.id'], ),
    sa.ForeignKeyConstraint(['parent_specialty_id'], ['specialties.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consultation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('agent_type', sa.Enum('COORDINATOR', 'TRIAGE', 'AVAILABILITY', 'ONBOARDING', 'POST_CONSULTATION', name='agenttype'), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('guardrail_triggered', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_notes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consultation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('is_visible_to_patient', sa.Boolean(), nullable=False),
    sa.Column('shared_with_professionals', sa.Boolean(), nullable=False),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('derivations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consultation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consultation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('professional_net', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('qr_expires_at', sa.DateTime(), nullable=True),
    sa.Column('bank_tx_id', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'RELEASED_TO_PROFESSIONAL', 'REFUNDED_PARTIAL', 'REFUNDED_FULL', 'DISPUTED', name='paymentstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('refund_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consultation_id')
    )
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consultation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_name', sa.String(length=200), nullable=False),
    sa.Column('patient_ci', sa.String(length=20), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('digital_hash', sa.String(length=256), nullable=False),
    sa.Column('qr_verify_code', sa.String(length=100), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('replaces_prescription_id', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['replaces_prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digital_hash'),
    sa.UniqueConstraint('qr_verify_code')
    )
    op.create_table('ratings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('consultation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consultation_id')
    )
    op.create_table('clinical_note_addenda',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('clinical_note_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinical_note_id'], ['clinical_notes.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('professional_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('payment_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings')
    op.drop_table('clinical_note_addenda')
    op.drop_table('ratings')
    op.drop_table('prescriptions')
    op.drop_table('payments')
    op.drop_table('derivations')
    op.drop_table('clinical_notes')
    op.drop_table('agent_logs')
    op.drop_table('specialty_proposals')
    op.drop_table('schedules')
    op.drop_table('professional_docs')
    op.drop_table('consultations')
    op.drop_table('sub_specialties')
    op.drop_table('professionals')
    op.drop_table('patients')
    op.drop_table('notifications')
    op.drop_table('audit_logs')
    op.drop_table('admins')
    op.drop_table('users')
    op.drop_table('specialties')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
